# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 09:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=datetime.datetime(2018, 8, 22, 9, 54, 52, 446307, tzinfo=utc), upload_to='articles/'),
            preserve_default=False,
        ),
    ]
